### PR TITLE
Check resolution before downloading

### LINKED ISSUE #6: Checks dimensions of files once downloaded, rather than within the JSON prior to download
There's a significant block of code in this script which appears to be present specifically to check that files are no smaller than the specified minimum Height and Width parameters.

The Height and Width values of the images are contained within the JSON:

data.children.data.preview.images.source.height
data.children.data.preview.images.source.width

We can filter out files that are below the minimum specified by the input parameters, just have to rework a bit of the code.  I'll see what I can do.

### PR DESCRIPTION
**Pull request by wi-ry**
Fixes #6

### CODE REVIEW

**Review by pandages — COMMENTED** [review]
Looks great!

I was doing something similar in my version, and had some issues with the nested If statements, where the Else statement to run the BITS download happens no matter the dimensions of the files.  I was in the process of tearing it apart and figuring out what's wrong when I saw your update.

I'll test your version!

**Review by pandages — CHANGES_REQUESTED** [review]
.data.preview.images[0].source.height  because "images" is an array.  Same with height.

**Comment by wi-ry** [comment]
> .data.preview.images[0].source.height because "images" is an array. Same with height.

Changing it as suggested causes errors for me:
image

image

**Comment by wi-ry** [comment]
Superseded by #8

**Pull request closed without merging**
